//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountstatu
    {
        public int AccountStatusID { get; set; }
        public string AccountStatus { get; set; }
        public string Description { get; set; }

        public List<userinfo> userinfos { get; set; } // Navigation property 
    }
}
