//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dapartment_Consumer
    {
        public int sno { get; set; }
        public string modification_status { get; set; }
        public string consumer_no { get; set; }
        public string consumer_name { get; set; }
        public string category { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<decimal> outstanding_Arrears { get; set; }
        public Nullable<decimal> after_rebate { get; set; }
        public string description { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
