//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int sno { get; set; }
        public string consumer_no { get; set; }
        public string consumer_code { get; set; }
        public string consumer_name { get; set; }
        public string consumer_address { get; set; }
        public string category { get; set; }
        public Nullable<decimal> area { get; set; }
        public string sqft_sqyd { get; set; }
        public Nullable<int> Storey { get; set; }
        public string zone { get; set; }
        public string town { get; set; }
        public string uc_no { get; set; }
        public string uc_name { get; set; }
        public string block { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string billing_month { get; set; }
        public Nullable<decimal> current_Charges { get; set; }
        public Nullable<decimal> outstanding_Arrears { get; set; }
        public Nullable<decimal> current_arrears { get; set; }
        public Nullable<decimal> consumer_service_charges { get; set; }
        public Nullable<decimal> within_duedate_amount { get; set; }
        public Nullable<decimal> consumer_surcharge { get; set; }
        public Nullable<decimal> after_duedate_amount { get; set; }
        public string property_tag { get; set; }
        public string kmc_category { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<byte> status { get; set; }
        public string consumer_checkdigit { get; set; }
        public string billing_period_code { get; set; }
        public string barcode { get; set; }
        public Nullable<int> checkdigit_status { get; set; }
        public Nullable<System.DateTime> part_payment_createdon { get; set; }
        public string part_payment_createdby { get; set; }
        public Nullable<decimal> part_payment_arrears { get; set; }
        public string part_payment_into { get; set; }
        public Nullable<byte> rebate_status { get; set; }
        public string short_description { get; set; }
        public string Department_Arrears { get; set; }
        public Nullable<decimal> Arrears_15 { get; set; }
    }
}
