//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modify_impact
    {
        public int impactID { get; set; }
        public string inword { get; set; }
        public string modification_status { get; set; }
        public string consumer_no { get; set; }
        public string consumer_name { get; set; }
        public Nullable<decimal> previous_arrears { get; set; }
        public Nullable<decimal> after_correction { get; set; }
        public Nullable<decimal> difference { get; set; }
        public Nullable<decimal> difference_percentage { get; set; }
        public string impact { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
