//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modify_consumer
    {
        public int modify_consumerID { get; set; }
        public string inword_no { get; set; }
        public string modification_status { get; set; }
        public string consumer_no { get; set; }
        public string previous_name { get; set; }
        public string previous_surname { get; set; }
        public string previous_cnic { get; set; }
        public string previous_mobile { get; set; }
        public string previous_address { get; set; }
        public string new_name { get; set; }
        public string new_surname { get; set; }
        public string new_cnic { get; set; }
        public string new_mobile { get; set; }
        public string new_address { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string description { get; set; }
        public string approvedby { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
