//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modify_invoice
    {
        public int sno { get; set; }
        public string inword { get; set; }
        public string modification_status { get; set; }
        public string consumer_no { get; set; }
        public string previous_category { get; set; }
        public Nullable<decimal> previous_area { get; set; }
        public Nullable<int> previous_Storey { get; set; }
        public Nullable<decimal> previous_current_Charges { get; set; }
        public Nullable<decimal> previous_outstanding_Arrears { get; set; }
        public string new_category { get; set; }
        public Nullable<decimal> new_area { get; set; }
        public Nullable<int> new_storey { get; set; }
        public Nullable<decimal> new_current_Charge { get; set; }
        public Nullable<decimal> new_outstanding_Arrears { get; set; }
        public string zone { get; set; }
        public string town { get; set; }
        public string billing_month { get; set; }
        public Nullable<decimal> consumer_surcharge { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string description { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
