//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUCTBill_Records
    {
        public int MUCTBillID { get; set; }
        public string ConsumerNo { get; set; }
        public string Zone { get; set; }
        public string Town { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string createdby { get; set; }
    }
}
