//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertytype
    {
        public int propertyTypeID { get; set; }
        public string propertyTypeName { get; set; }
        public string PropertyCode { get; set; }
        public string SizeIn { get; set; }
    }
}
