//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rebate_cancle_history
    {
        public int RCID { get; set; }
        public string inwordno { get; set; }
        public string consumer_no { get; set; }
        public string consumer_name { get; set; }
        public Nullable<decimal> pervious_outstanding { get; set; }
        public Nullable<decimal> after_rebate_outstanding { get; set; }
        public Nullable<decimal> difference { get; set; }
        public Nullable<decimal> difference_percentage { get; set; }
        public string cancledby { get; set; }
        public Nullable<System.DateTime> cancledon { get; set; }
    }
}
