//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchingsheet
    {
        public int SearchID { get; set; }
        public Nullable<int> inword { get; set; }
        public string consumer_no { get; set; }
        public string zone { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
