//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchinsheetsuspended
    {
        public int SSID { get; set; }
        public string InwordNo { get; set; }
        public string Consumer_No { get; set; }
        public string Department { get; set; }
        public string Zone { get; set; }
        public string Twon { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
    }
}
