//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategoryproperty
    {
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public string subcategorycode { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
