//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmcmvc.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class userinfo
    {
        
        public int userinfoID { get; set; }
        [Required(ErrorMessage = "Username is Required")]
        public string Username { get; set; }
        public string FullName { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required]
        [Phone]
        public string Mobile { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        
        public string CNIC { get; set; }
        [Required]
        public string Address { get; set; }
        public Nullable<int> RoleID { get; set; }

        public List<role> rolelist { get; set; }
        
        public role role { get; set; } // Navigate Property
        
        [Required]
        [NotMapped]
        public string Rolename { get; set; }
        
        public Nullable<int> AccountStatusID { get; set; }
        public List<accountstatu> statuslist { get; set; }
        public accountstatu accountstatu { get; set; }

        [Required]
        [NotMapped]
        public string status { get; set; }

    }
}
